# Generated by Django 4.1.3 on 2022-12-01 21:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0002_item_question_bid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bid',
            name='end',
        ),
        migrations.RemoveField(
            model_name='bid',
            name='start',
        ),
        migrations.AddField(
            model_name='bid',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Bid time'),
            preserve_default=False,
        ),
    ]
