# Generated by Django 4.1.3 on 2022-12-01 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0003_remove_bid_end_remove_bid_start_bid_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='response',
            field=models.TextField(blank=True, default=None, max_length=1000, null=True),
        ),
    ]
