# Generated by Django 4.1.3 on 2022-12-08 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0005_alter_bid_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='condition',
            field=models.CharField(choices=[('NEW', 'NEW'), ('UE', 'USED - EXCELLENT'), ('UG', 'USED - GOOD'), ('UA', 'USED - ACCEPTABLE')], default='NEW', max_length=20),
        ),
    ]
