# Generated by Django 4.1.2 on 2022-12-08 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0005_alter_bid_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='picture',
            field=models.CharField(default='imageHere', max_length=255),
            preserve_default=False,
        ),
    ]
