# Generated by Django 4.1.2 on 2022-12-08 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0006_user_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='picture',
        ),
    ]
