# Generated by Django 4.1.3 on 2022-12-11 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0007_alter_item_owner'),
        ('auction', '0007_remove_user_picture'),
    ]

    operations = [
    ]
