# Generated by Django 4.1.2 on 2022-12-11 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0008_user_city_user_dob_user_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='city',
        ),
        migrations.RemoveField(
            model_name='user',
            name='dob',
        ),
        migrations.RemoveField(
            model_name='user',
            name='picture',
        ),
    ]
