# Generated by Django 4.1.2 on 2022-12-12 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0007_alter_item_owner'),
        ('auction', '0010_user_city_user_dob_user_picture'),
    ]

    operations = [
    ]
